# Generated by Django 6.0.1 on 2026-01-27 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (auto-calculated)', max_digits=5, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=20)),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary (little or no exercise)'), ('LIGHTLY_ACTIVE', 'Lightly Active (exercise 1-3 days/week)'), ('MODERATELY_ACTIVE', 'Moderately Active (exercise 3-5 days/week)'), ('VERY_ACTIVE', 'Very Active (exercise 6-7 days/week)'), ('EXTREMELY_ACTIVE', 'Extremely Active (physical job or training twice/day)')], max_length=20)),
                ('dietary_preference', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('MIXED', 'Mixed (Both)')], max_length=20)),
                ('diabetes_status', models.CharField(choices=[('NONE', 'None'), ('PRE_DIABETIC', 'Pre-Diabetic'), ('TYPE_1', 'Type 1 Diabetes'), ('TYPE_2', 'Type 2 Diabetes')], default='NONE', max_length=20)),
                ('goal', models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('MAINTAIN_WEIGHT', 'Maintain Weight'), ('GAIN_WEIGHT', 'Gain Weight')], default='MAINTAIN_WEIGHT', max_length=20)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Daily food budget in NPR', max_digits=8, null=True)),
                ('daily_calories', models.IntegerField(blank=True, help_text='Daily calorie requirement', null=True)),
                ('daily_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
