# Generated by Django 6.0.1 on 2026-02-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cluster_id',
            field=models.IntegerField(blank=True, help_text='K-Means cluster assignment', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cluster_name',
            field=models.CharField(blank=True, help_text='Cluster label', max_length=50),
        ),
    ]
