# Generated by Django 6.0.1 on 2026-01-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('MEAL', 'Complete Meal'), ('GRAIN', 'Grain'), ('LEGUME', 'Legume'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('MEAT', 'Meat'), ('DAIRY', 'Dairy'), ('SNACK', 'Snack'), ('BEVERAGE', 'Beverage'), ('DESSERT', 'Dessert')], max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Calories in kcal', max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, help_text='Carbs in grams', max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Fat in grams', max_digits=5)),
                ('glycemic_index', models.IntegerField(help_text='GI value (0-100)')),
                ('gi_category', models.CharField(blank=True, choices=[('LOW', 'Low (0-55)'), ('MEDIUM', 'Medium (56-69)'), ('HIGH', 'High (70-100)')], max_length=10)),
                ('is_diabetes_friendly', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('meal_type', models.CharField(help_text='e.g., Breakfast,Lunch,Dinner', max_length=100)),
                ('average_price', models.DecimalField(decimal_places=2, help_text='Price in NPR', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['food_name'],
            },
        ),
    ]
