# Generated by Django 6.0.1 on 2026-02-08 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile_cluster_id_userprofile_cluster_name'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nutritional_accuracy', models.DecimalField(decimal_places=2, help_text='Percentage accuracy', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breakfast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_plans', to='foods.food')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_plans', to='foods.food')),
                ('lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_plans', to='foods.food')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
