# Generated by Django 6.0.1 on 2026-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_plans', to='foods.food'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_plans', to='foods.food'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_plans', to='foods.food'),
        ),
    ]
